source 'https://github.com/CocoaPods/Specs.git'

target 'TLAnimatedSegue', :exclusive => true do
  pod "TLAnimatedSegue", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TLAnimatedSegue", :path => "../"

  
end
